### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by lex111** [rectorphp/the-power-of-automated-refactoring-feedback#21]
Would be glad to translate the book into Russian.

**Comment by lex111** [comment]
Alright, let's wait for PHP 8.1, this probably makes sense.

**Comment by matthiasnoback** [comment]
Hey @lex111 ! Thanks for submitting this issue here :)

I would like to look into translations, but would also like to do a better job at managing versions than just having separate repositories and having to keep up with change logs. We need automation here, and it's going to be some effort to get the project ready for it. Let's put this on the roadmap @TomasVotruba ;)

**Comment by TomasVotruba** [comment]
Agreed with @matthiasnoback, we need to improve the book automation first, so we can release only diff translations in years to come.

Let's close this for now, to avoid attracting more translations at the moment.

**Comment by dvc** [comment]
Hello, everyone!

Sorry for writing to closed issue. Tomas asked me to  write here instead of email.

I think that preparation to translatioin should be started before new version of book. Because it will hard work to transform after.
I'm not a professional in translations. In my mind it's looks like:

1. Split book by chapters, paragraphs and special objects. Set id to every item: "chapterX.paragraphY", "codeBlockA.commentB"
2. Create xliff with this keys
3. Main content set as html, epub, pdf,..  twig templates with (optional) latex markdown. And add translate snippets to it.
4. Upload one or more xliff to online translate service like https://pootle.translatehouse.org/
5. Sync translated xliff back to project
6. Configure CI to build localized sources from twig and xliff. And to target format (html, epub, pdf) after that.

**Comment by TomasVotruba** [comment]
Thanks for proposals of exact steps. For me, we can go for it, as long as there is no extra maintenance for changing manuscript = the split to xliff must happen in some automated fashion. E.g. `chapter.paragraph#`. I would go crazy if I'd have to jump between keywords and text :)

I imagine this automated process would also report change of original content so it would be easier to maintain.

**Comment by matthiasnoback** [comment]
To be very honest, this sounds like a lot of work, and I'm not sure it would play well with the current setup and the manuscript generator that we use for this project.

**Comment by dvc** [comment]
> the manuscript generator

Never work with it. Can you post link to this project?

>  I would go crazy if I'd have to jump between keywords and text :)

Do you mean: manuscript source + some "key comments" -> xliff ? Sounds good.

> this sounds like a lot of work

Can i help you with some of this work?
